### ISSUE TITLE
Upload visualisation very slow for large datasets

### ISSUE THREAD

**Issue by geezacoleman** [Sydney-Informatics-Hub/Weed-AI#488]
Currently uploading the deepweeds dataset and while it's only ~500 MB the visualisation is incredibly slow as it tries to preview every image of the 17,000. My internet connection is possibly part of the issue, but does it need to visualise every image in the dataset prior to upload?

**Comment by jnothman** [comment]
Maybe preview should turn off the moment it reaches > 200 images. Is that feasible, @ElevnLi?

**Comment by geezacoleman** [comment]
At the moment it seems like anything over a few thousand images won't be possible to upload. DeepWeeds gets to ~16900 remaining and then ticks down by about 1 image/second. Initially it uploads at about ~40/sec.

**Comment by geezacoleman** [comment]
It seems to reload the entire preview set each time it presents a new image. Could explain why it get slower over time?

**Comment by ElevnLi** [comment]
Hey @geezacoleman, can you have a try again? I disabled preview for over 100 images and changed a bit the way uploaded images are sent to the server. Maybe start with uploading 1000 images and let me know which part of process is still holding the speed down. Thanks.

**Comment by geezacoleman** [comment]
Thanks @ElevnLi - it still is previewing all the images even when I upload over 1000. It's much faster than before (roughly 5 images/second), but if you change tabs/click away from the site while it is previewing them, then the site crashes and reloads and you lose any upload progress.

**Comment by jnothman** [comment]
Do you know if that problem of changing tabs might have been an issue in the previous version, @geezacoleman?

**Comment by jnothman** [comment]
Hi Guy, as far as we can tell it's still working in the background, even when you change tabs. Returning to the uploader tab it can look white for a moment, but you need to wait for it to render. We are aware that it could be more efficient, but we don't have budget to look into it much more closely.

We have noticed an issue where the uploading stalls, and you need to reselect and upload the images. We don't yet have a path to debugging this.

The issue with not displaying more than 100 images is resolved.

**Comment by geezacoleman** [comment]
Seems to be working ok now - estimating about 45 mins for the entire deep weeds dataset, but a lot faster than before. Thanks for working that out.

**Comment by geezacoleman** [comment]
Still getting the 'There are identical images in the image directory.' error once all images upload - any ideas? For some reason it also seems to miss images that are in the directory and selected with the initial lot. So I just reselect everything and then it determines which are duplicates and which need loading.

**Comment by jnothman** [comment]
Had you deployed #499 on django and celery, @ElevnLi?

**Comment by ElevnLi** [comment]
@geezacoleman Sorry, I hadn't deployed the changes. You can try again to see if it's working better.

**Comment by ElevnLi** [comment]
@geezacoleman Also you can try uploading a zip file containing images for that dataset. Just deployed it.. Hopefully it works.

**Comment by ElevnLi** [comment]
<img width="1792" alt="Screen Shot 2021-06-18 at 6 16 00 pm" src="https://user-images.githubusercontent.com/51065213/122530373-c0347300-d061-11eb-80ee-1977938e2ea5.png">

**Comment by geezacoleman** [comment]
Thanks ELevn - unfortunately I now get this error on the zip file upload. I'll try uploading the images again and seeing if it works without the duplicate image error.
![image](https://user-images.githubusercontent.com/51358498/122581163-5e9de580-d01c-11eb-8582-524ffb349713.png)

**Comment by ElevnLi** [comment]
@geezacoleman I increased the request size from 100MB to 5000MB in the gateway. You can try to upload the zip again, not sure if it helps.

**Comment by geezacoleman** [comment]
I just tried the individual upload again, but still got the "There are identical images in the image directory." error. I'll try the zip file now. One repeating issue with the individual uploader is that it skips images that are definitely in the selection. So it will stop on 190 images missing, so I reselect images again, but it will stop on 20 images and do the same again. The numbers vary but the process seems to repeat.

**Comment by geezacoleman** [comment]
The zip file upload works but then I still get the "There are identical images in the image directory." error. I can't say I've been through the deepweeds dataset to check - it's possible there are? In that error, is it possible to tell you which files it considers identical?

**Comment by ElevnLi** [comment]
I think overall uploading zip is a much better approach to resolve large dataset and it should work functionally. Glad to see that.
Is this upload very urgent? If yes, I can give you a quick fix today to at least show you which images are identical. Otherwise, I'll discuss with Joel next Monday and come out a better solution.

**Comment by ElevnLi** [comment]
@geezacoleman I had a brief check using script and it shows the following images are considered the same hash-wise:
```
{
  "3fefefeb8e83a0781a0f02c00.jpg":[
    "20180105-095833-3.jpg",
    "20180105-095816-3.jpg"
  ],
  "06c3e18c07d876785a17f3f4e.jpg":[
    "20180109-085954-2.jpg",
    "20180109-090005-2.jpg"
  ],
  "c4b00793f0e4380c038af23c7.jpg":[
    "20171203-164605-3.jpg",
    "20171203-164604-3.jpg"
  ],
  "1f87e1f87c1e0713c5f4c0024.jpg":[
    "20180109-110201-2.jpg",
    "20180109-110200-2.jpg"
  ],
  "63dff3fc3f07c190f40f03c7f.jpg":[
    "20180125-132851-2.jpg",
    "20180125-132850-2.jpg"
  ],
  "f32de87a06a0f058122ef3b5d.jpg":[
    "20180105-093909-3.jpg",
    "20180105-093850-3.jpg"
  ],
  "01c0701c0701ce73dcfbfefff.jpg":[
    "20180125-094449-2.jpg",
    "20180125-094503-2.jpg"
  ],
  "03c0f43f4b0040d1fc7f3fc7f.jpg":[
    "20180112-103533-2.jpg",
    "20180112-103542-2.jpg"
  ],
  "3e0e00c0700f03ccf3382300d.jpg":[
    "20180322-111349-2.jpg",
    "20180322-111339-2.jpg"
  ],
  "aecfb17c4e6d9960d83c04200.jpg":[
    "20171218-121959-3.jpg",
    "20171218-122019-3.jpg"
  ],
  "9fe7f99c4701c1f03c0380604.jpg":[
    "20180125-094451-2.jpg",
    "20180125-094438-2.jpg"
  ],
  "01c1683c0f03c1e0fc3f0dc07.jpg":[
    "20180105-093543-3.jpg",
    "20180105-093556-3.jpg"
  ],
  "f03c0f03c0e0380e0380e0380.jpg":[
    "20170207-142255-0.jpg",
    "20180112-092440-2.jpg"
  ],
  "e1f83f43f0fc3e0da360d8120.jpg":[
    "20171121-074015-1.jpg",
    "20171121-074016-1.jpg"
  ],
  "738ef1bc6f49c37c0e03c0c21.jpg":[
    "20171218-110346-3.jpg",
    "20171218-110417-3.jpg"
  ]
}
```
Let me know if you think they shouldn't be the same, and we might need to make the hash more precise.

**Comment by jnothman** [comment]
Oh! :o I thought I checked these, but apparently not...

I can confirm these appear to be identical images.

I think we might need to update our deepweeds converter to reflect this.

**Comment by jnothman** [comment]
Image pairs such as
```
"01c0701c0701ce73dcfbfefff.jpg":[
    "20180125-094449-2.jpg",
    "20180125-094503-2.jpg"
  ],
``` are not md5 identical, though this is what they look like (and what our duplicate detector picks up):
![20180125-094449-2](https://user-images.githubusercontent.com/78827/122695526-f2251f80-d283-11eb-89df-14d8575fedc2.jpg)
![20180125-094503-2](https://user-images.githubusercontent.com/78827/122695534-f81b0080-d283-11eb-9e06-a798c2865513.jpg)

**Comment by jnothman** [comment]
Certainly not identical. @geezacoleman, it might be worth bringing Alex into the conversation: can we deduplicate images before uploading them?

**Comment by jnothman** [comment]
```
  "f03c0f03c0e0380e0380e0380.jpg":[
    "20170207-142255-0.jpg",
    "20180112-092440-2.jpg"
  ],
```
Seems to be a false positive hash collision :(

![20170207-142255-0](https://user-images.githubusercontent.com/78827/122695774-c0f91f00-d284-11eb-8653-94fa7450c2a3.jpg)
![20180112-092440-2](https://user-images.githubusercontent.com/78827/122695783-c5bdd300-d284-11eb-8f21-036ea01a4a94.jpg)

**Comment by jnothman** [comment]
I can confirm that all but that pair are perceptually the same image (with some lighting differences, slight offsets, etc.)

**Comment by geezacoleman** [comment]
> Image pairs such as
> 
> ```
> "01c0701c0701ce73dcfbfefff.jpg":[
>     "20180125-094449-2.jpg",
>     "20180125-094503-2.jpg"
>   ],
> ```
> 
> are not md5 identical, though this is what they look like (and what our duplicate detector picks up):
> ![20180125-094449-2](https://user-images.githubusercontent.com/78827/122695526-f2251f80-d283-11eb-89df-14d8575fedc2.jpg)
> ![20180125-094503-2](https://user-images.githubusercontent.com/78827/122695534-f81b0080-d283-11eb-9e06-a798c2865513.jpg)

Ok, thanks for working that out. I'll send Alex an email with the list of duplicate images and ask how he would like to resolve it.  This pair look identical but as you mention, only the `"20170207-142255-0.jpg", "20180112-092440-2.jpg"` pair seem to be wildly different.

**Comment by geezacoleman** [comment]
> I think overall uploading zip is a much better approach to resolve large dataset and it should work functionally. Glad to see that.
> Is this upload very urgent? If yes, I can give you a quick fix today to at least show you which images are identical. Otherwise, I'll discuss with Joel next Monday and come out a better solution.

Very much agreed that the zip file upload is easier! Saved 95% of the time/resources required and much easier to make multiple efforts when it doesn't take as long. Are there downsides to this method?

**Comment by ElevnLi** [comment]
> > I think overall uploading zip is a much better approach to resolve large dataset and it should work functionally. Glad to see that.
> > Is this upload very urgent? If yes, I can give you a quick fix today to at least show you which images are identical. Otherwise, I'll discuss with Joel next Monday and come out a better solution.
> 
> Very much agreed that the zip file upload is easier! Saved 95% of the time/resources required and much easier to make multiple efforts when it doesn't take as long. Are there downsides to this method?

Hey Guy, the only drawback of zip upload is that you cannot modify each image and you have upload them together. Other than that, it's good to go.

**Comment by ElevnLi** [comment]
We are using [hash size 10](https://github.com/Sydney-Informatics-Hub/Weed-AI/blob/8de44388c12112b6becbabea45b5454fd5c8a5cf/weedcoco/repo/deposit.py#L80) to identify images. I found that the 2 images are different for hash size to be 8 or 16 but they are the same when hash size is 10. And this only happen to this image pair.
```bash
>>> str(imagehash.average_hash(PIL.Image.open('/Users/elevn/Documents/images/20180112-092440-2.jpg'), hash_size=8))
'e0e0e0e0e0e0e0c0'
>>> str(imagehash.average_hash(PIL.Image.open('/Users/elevn/Documents/images/20170207-142255-0.jpg'), hash_size=8))
'f0e0e0e0c0c0c0c0'
>>> str(imagehash.average_hash(PIL.Image.open('/Users/elevn/Documents/images/20180112-092440-2.jpg'), hash_size=10))
'f03c0f03c0e0380e0380e0380'
>>> str(imagehash.average_hash(PIL.Image.open('/Users/elevn/Documents/images/20170207-142255-0.jpg'), hash_size=10))
'f03c0f03c0e0380e0380e0380'
>>> str(imagehash.average_hash(PIL.Image.open('/Users/elevn/Documents/images/20180112-092440-2.jpg'), hash_size=16))
'f600fe00fe00fe00fe00fc00fc00fc00f800fc00f800f800d800d8005800f800'
>>> str(imagehash.average_hash(PIL.Image.open('/Users/elevn/Documents/images/20170207-142255-0.jpg'), hash_size=16))
'fe00fe40f880fc00ee00fc00fc00fc00f800f800f800f800f000f000f800b000'
```
I think we should change the hash size to either 8 or 16.

**Comment by geezacoleman** [comment]
> > > I think overall uploading zip is a much better approach to resolve large dataset and it should work functionally. Glad to see that.
> > > Is this upload very urgent? If yes, I can give you a quick fix today to at least show you which images are identical. Otherwise, I'll discuss with Joel next Monday and come out a better solution.
> > 
> > 
> > Very much agreed that the zip file upload is easier! Saved 95% of the time/resources required and much easier to make multiple efforts when it doesn't take as long. Are there downsides to this method?
> 
> Hey Guy, the only drawback of zip upload is that you cannot modify each image and you have upload them together. Other than that, it's good to go.

Ok great - I think the zip file method is what we should recommend then for most/all datasets over 100 images then.

**Comment by geezacoleman** [comment]
> We are using [hash size 10](https://github.com/Sydney-Informatics-Hub/Weed-AI/blob/8de44388c12112b6becbabea45b5454fd5c8a5cf/weedcoco/repo/deposit.py#L80) to identify images. I found that the 2 images are different for hash size to be 8 or 16 but they are the same when hash size is 10. And this only happen to this image pair.
> 
> ```shell
> >>> str(imagehash.average_hash(PIL.Image.open('/Users/elevn/Documents/images/20180112-092440-2.jpg'), hash_size=8))
> 'e0e0e0e0e0e0e0c0'
> >>> str(imagehash.average_hash(PIL.Image.open('/Users/elevn/Documents/images/20170207-142255-0.jpg'), hash_size=8))
> 'f0e0e0e0c0c0c0c0'
> >>> str(imagehash.average_hash(PIL.Image.open('/Users/elevn/Documents/images/20180112-092440-2.jpg'), hash_size=10))
> 'f03c0f03c0e0380e0380e0380'
> >>> str(imagehash.average_hash(PIL.Image.open('/Users/elevn/Documents/images/20170207-142255-0.jpg'), hash_size=10))
> 'f03c0f03c0e0380e0380e0380'
> >>> str(imagehash.average_hash(PIL.Image.open('/Users/elevn/Documents/images/20180112-092440-2.jpg'), hash_size=16))
> 'f600fe00fe00fe00fe00fc00fc00fc00f800fc00f800f800d800d8005800f800'
> >>> str(imagehash.average_hash(PIL.Image.open('/Users/elevn/Documents/images/20170207-142255-0.jpg'), hash_size=16))
> 'fe00fe40f880fc00ee00fc00fc00fc00f800f800f800f800f000f000f800b000'
> ```
> 
> I think we should change the hash size to either 8 or 16.

@ElevnLi - did you end up changing the hash size? I removed the genuine 14 duplicates and tried reuploading but still got the error that there were duplicate images in the folder. Image/label count is now 17495, so I'm fairly confident they are gone.

**Comment by jnothman** [comment]
It might not be in the currently deployed version, sorry. Sorry for the troubles; we will merge this code and deploy today

From: Guy Coleman ***@***.***>
Reply to: Sydney-Informatics-Hub/Weed-AI ***@***.***>
Date: Thursday, 1 July 2021 at 8:54 am
To: Sydney-Informatics-Hub/Weed-AI ***@***.***>
Cc: "joel.nothman" ***@***.***>, Comment ***@***.***>
Subject: Re: [Sydney-Informatics-Hub/Weed-AI] Upload visualisation very slow for large datasets (#488)


We are using hash size 10<https://github.com/Sydney-Informatics-Hub/Weed-AI/blob/8de44388c12112b6becbabea45b5454fd5c8a5cf/weedcoco/repo/deposit.py#L80> to identify images. I found that the 2 images are different for hash size to be 8 or 16 but they are the same when hash size is 10. And this only happen to this image pair.

>>> str(imagehash.average_hash(PIL.Image.open('/Users/elevn/Documents/images/20180112-092440-2.jpg'), hash_size=8))

'e0e0e0e0e0e0e0c0'

>>> str(imagehash.average_hash(PIL.Image.open('/Users/elevn/Documents/images/20170207-142255-0.jpg'), hash_size=8))

'f0e0e0e0c0c0c0c0'

>>> str(imagehash.average_hash(PIL.Image.open('/Users/elevn/Documents/images/20180112-092440-2.jpg'), hash_size=10))

'f03c0f03c0e0380e0380e0380'

>>> str(imagehash.average_hash(PIL.Image.open('/Users/elevn/Documents/images/20170207-142255-0.jpg'), hash_size=10))

'f03c0f03c0e0380e0380e0380'

>>> str(imagehash.average_hash(PIL.Image.open('/Users/elevn/Documents/images/20180112-092440-2.jpg'), hash_size=16))

'f600fe00fe00fe00fe00fc00fc00fc00f800fc00f800f800d800d8005800f800'

>>> str(imagehash.average_hash(PIL.Image.open('/Users/elevn/Documents/images/20170207-142255-0.jpg'), hash_size=16))

'fe00fe40f880fc00ee00fc00fc00fc00f800f800f800f800f000f000f800b000'

I think we should change the hash size to either 8 or 16.

@ElevnLi<https://github.com/ElevnLi> - did you end up changing the hash size? I removed the genuine 14 duplicates and tried reuploading but still got the error that there were duplicate images in the folder. Image/label count is now 17495, so I'm fairly confident they are gone.

**Comment by jnothman** [comment]
The version without false identifications of duplicates should be deployed now.

The only pairs that should be triggering a clash now are (20171218-110346-3.jpg, 20171218-110417-3.jpg) and (20180125-132851-2.jpg, 20180125-132850-2.jpg).

**Comment by geezacoleman** [comment]
No worries, thanks! Are they two additional duplicate pairs to the 14 removed?
________________________________

**Comment by jnothman** [comment]
No, they are a subset of those previously matched
